# Nama workflow yang akan tampil di tab Actions GitHub
name: Deploy to VPS

# Pemicu workflow: dijalankan setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - master

# Daftar pekerjaan (jobs) yang akan dieksekusi
jobs:
  deploy:
    # Menggunakan sistem operasi Ubuntu versi terbaru
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dijalankan
    steps:
      # Langkah 1: Mengambil kode dari repository (git checkout)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menjalankan perintah di VPS melalui SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # Ambil data kredensial dari GitHub Secrets
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}

          # Perintah yang akan dieksekusi di dalam VPS
          script: |
            # Masuk ke direktori proyek
            cd /root/kamisama-v0

            # Tarik perubahan terbaru dari branch main
            git pull origin main
